name: datacontext
description: A starting point for Dart libraries or applications.
version: 1.0.1
# homepage: https://www.example.com
repository: https://github.com/eakeur/data_context

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  provider: ^5.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  
  
